#!/usr/bin/env python3
"""
mcpp_generator.py
=================

Realistic benchmark instance generator for the Mixed-Case Palletization Problem
(MCPP) / 3D Bin Packing Problem (3DBPP).

The core generator is a reimplementation of the instance generator described in

    S. Elhedhli, F. Gzara, B. Yildiz (2019).
    "Three-Dimensional Bin Packing and Mixed-Case Palletization."
    INFORMS Journal on Optimization 1(4), 323-352.   Section 7.1, Tables 2-4.

Their generator was trained on 166,406 industrial items (73,978 distinct) and
replaces the classical Martello et al. (2000) random instances, which are
unrealistic: ~4.31 items per bin versus >=90 items per bin in real data.

Model (paper, Section 7.1)
--------------------------
An item is *not* generated by drawing three independent side lengths. Instead
the paper draws shape ratios and a volume, which keeps the dimensions properly
related to each other:

    depth / width   ~ Normal(0.695, 0.118)
    height / width  ~ Lognormal(-0.654, 0.453)
    repetition      ~ Lognormal(0.544, 0.658)      (copies of the same SKU)
    volume          ~ one of 5 k-means categories, mixed per instance class

    v = w * d * h = w * (p*w) * (q*w) = p*q*w^3   =>   w = (v/(p*q))^(1/3)

Volume categories (dm^3), from k-means with k = 5 on the industry data:
    1: [ 2.72,  12.04]   72,037 items
    2: [12.05,  20.23]   55,436 items
    3: [20.28,  32.42]   26,254 items
    4: [32.44,  54.08]    9,304 items
    5: [54.31, 100.21]    3,376 items

Four instance classes were obtained by clustering real orders by their category
mix (paper Table 3). Class 1 = medium boxes, Class 4 = many small boxes.

Verification of the reimplementation
------------------------------------
Paper Table 4 reports the centroid (w, d, h, v) of the *generated* data as

    class 1: (338.80, 232.81, 181.95, 13.72)
    class 2: (336.89, 231.18, 180.51, 13.53)
    class 3: (312.77, 215.31, 168.00, 10.97)
    class 4: (304.86, 209.66, 164.87, 10.19)

Running `python mcpp_generator.py validate` reproduces classes 1, 3 and 4 to
within ~2 % on every dimension, which confirms the reconstruction of the
(unpublished) generator code. Class 2 comes out heavier (mean volume ~19.8 dm^3
instead of 13.53) because it is the only class with a substantial share of the
two largest volume categories (7.94 % + 3.28 %). The paper's own numbers are
suspicious here: its *industry* class-2 centroid volume is 19.54 dm^3, i.e. very
close to what this generator produces, while the reported *generated* value of
13.53 is almost identical to class 1. Two explanations are consistent with the
text: Table 4 may report a k-means centroid (pulled towards the dense small-box
cluster) rather than an arithmetic mean, or volumes may be drawn from a
decreasing density inside each category rather than uniformly. Uniform sampling
inside the category interval is used here because it is the only choice the
paper's description supports.

Extensions for the retail pallet-loading task
---------------------------------------------
The paper only generates geometry. Everything below is an *extension* and is
clearly marked as such in the code and in the output metadata ("extended": true):

  * weight, derived from a product-family-specific density,
  * product family and a food/chemical flag (for the vertical-ordering rule
    "food above cleaning agents"),
  * load-bearing capacity (kPa) and a fragile flag,
  * an orientation flag (`upright_only`, e.g. liquids) restricting rotations,
  * a store zone and a retrieval priority (picking sequence).

These follow common practice in the container-loading literature (e.g. the
load-bearing convention sigma_i ~ U[0, 3*h_i] of Junqueira et al. 2012) but are
*not* fitted to the industry data of Elhedhli et al.

Usage
-----
  # one instance, human-readable summary + JSON
  python mcpp_generator.py single --class 2 --items 1000 --seed 7 -o out/

  # D-Wave 3D-bin-packing input plus rich metadata JSON
  python mcpp_generator.py single --class 4 --items 20 --seed 7 \
      --formats solver,json --solver-bins 2 -o input/generated/

  # the full 4 classes x {50..2000} x 5 replications benchmark set (160 files)
  python mcpp_generator.py batch -o benchmark/

  # reproduce Table 4 of the paper
  python mcpp_generator.py validate

  # a tiny didactic instance for a first MIP model
  python mcpp_generator.py single --class 4 --items 12 --seed 1 --no-extended

Only the Python standard library is required.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import random
import statistics
from dataclasses import dataclass, asdict, field
from typing import Dict, List, Optional, Sequence, Tuple

# --------------------------------------------------------------------------- #
# 1. Parameters taken directly from Elhedhli et al. (2019)
# --------------------------------------------------------------------------- #

# Table 2: fitted distributions for the item shape characteristics.
DW_RATIO_MEAN, DW_RATIO_SD = 0.695, 0.118        # depth/width   ~ Normal
HW_RATIO_MU, HW_RATIO_SIGMA = -0.654, 0.453      # height/width  ~ Lognormal
REP_MU, REP_SIGMA = 0.544, 0.658                 # repetition    ~ Lognormal

# k-means volume categories in dm^3 (1 dm^3 = 1e6 mm^3).
VOLUME_CATEGORIES: List[Tuple[float, float]] = [
    (2.72, 12.04),
    (12.05, 20.23),
    (20.28, 32.42),
    (32.44, 54.08),
    (54.31, 100.21),
]

# Table 3: percentage of items of each volume category per instance class.
CLASS_MIX: Dict[int, List[float]] = {
    1: [28.48, 58.75, 12.67, 0.10, 0.00],
    2: [33.08, 32.36, 23.34, 7.94, 3.28],
    3: [66.88, 24.75, 5.70, 2.60, 0.08],
    4: [78.58, 13.16, 6.33, 1.78, 0.15],
}

# Table 4: centroids of the *generated* data, used as a regression test.
PAPER_GENERATED_CENTROIDS: Dict[int, Tuple[float, float, float, float]] = {
    1: (338.80, 232.81, 181.95, 13.72),
    2: (336.89, 231.18, 180.51, 13.53),
    3: (312.77, 215.31, 168.00, 10.97),
    4: (304.86, 209.66, 164.87, 10.19),
}
PAPER_GENERATED_AVG_DIST: Dict[int, float] = {1: 1.80, 2: 1.87, 3: 1.80, 4: 1.74}

# Instance sizes used in the paper (5 replications each -> 160 instances).
PAPER_SIZES: List[int] = [50, 100, 150, 200, 500, 1000, 1500, 2000]

# Sanity bounds so that degenerate ratio draws cannot create impossible boxes.
MIN_SIDE_MM = 50.0
DW_RATIO_BOUNDS = (0.25, 1.00)      # depth never exceeds width
HW_RATIO_BOUNDS = (0.12, 3.00)


# --------------------------------------------------------------------------- #
# 2. Bin / pallet definitions
# --------------------------------------------------------------------------- #

@dataclass(frozen=True)
class Pallet:
    """Loading space, all dimensions in mm."""
    width: float          # W, along x
    depth: float          # D, along y
    height: float         # H, along z (usable stacking height)
    name: str = "custom"
    max_payload_kg: float = 1000.0

    @property
    def volume_mm3(self) -> float:
        return self.width * self.depth * self.height

    @property
    def volume_dm3(self) -> float:
        return self.volume_mm3 / 1e6


# The bin used throughout Elhedhli et al. (their industrial partner's pallet).
PALLET_ELHEDHLI = Pallet(1200.0, 800.0, 2055.0, "elhedhli-2055", 1000.0)

# The Euro pallet of the retail assignment: 120 x 80 cm, max load height 180 cm.
PALLET_EURO_180 = Pallet(1200.0, 800.0, 1800.0, "euro-180", 1000.0)

PALLETS: Dict[str, Pallet] = {p.name: p for p in (PALLET_ELHEDHLI, PALLET_EURO_180)}


# --------------------------------------------------------------------------- #
# 3. Product families (EXTENSION - not part of the paper)
# --------------------------------------------------------------------------- #

@dataclass(frozen=True)
class Family:
    name: str
    share: float                       # probability of drawing this family
    density_kg_m3: Tuple[float, float]  # gross density range of the packed case
    is_food: bool
    is_chemical: bool
    fragile_prob: float                # probability the case must stay on top
    upright_prob: float                # probability that rotation is restricted
    zone: str                          # store area -> drives retrieval priority


FAMILIES: List[Family] = [
    Family("beverages",       0.18, (700.0, 1050.0), True,  False, 0.05, 0.85, "drinks"),
    Family("dry_food",        0.26, (200.0,  480.0), True,  False, 0.06, 0.15, "dry_goods"),
    Family("canned_food",     0.12, (500.0,  900.0), True,  False, 0.02, 0.30, "dry_goods"),
    Family("snacks_bakery",   0.10, ( 60.0,  180.0), True,  False, 0.45, 0.20, "bakery"),
    Family("chilled_food",    0.08, (350.0,  700.0), True,  False, 0.20, 0.60, "chilled"),
    Family("household_chem",  0.12, (450.0,  900.0), False, True,  0.05, 0.90, "household"),
    Family("personal_care",   0.08, (200.0,  450.0), False, True,  0.15, 0.55, "health"),
    Family("non_food",        0.06, (120.0,  400.0), False, False, 0.25, 0.25, "general"),
]

# Order in which the store areas are picked from the pallet (1 = needed first,
# i.e. should end up on top / easily accessible).
ZONE_PICK_ORDER: List[str] = [
    "chilled", "bakery", "drinks", "dry_goods", "household", "health", "general",
]

MAX_CASE_WEIGHT_KG = 25.0   # manual-handling limit; heavier cases are re-sampled


# --------------------------------------------------------------------------- #
# 4. Item representation
# --------------------------------------------------------------------------- #

@dataclass
class Item:
    id: int
    sku: int                     # items sharing an sku are geometrically identical
    width: float                 # mm, x
    depth: float                 # mm, y
    height: float                # mm, z
    volume_dm3: float
    volume_category: int         # 1..5

    # --- extension attributes (None when --no-extended) ---
    weight_kg: Optional[float] = None
    family: Optional[str] = None
    is_food: Optional[bool] = None
    is_chemical: Optional[bool] = None
    fragile: Optional[bool] = None
    load_bearing_kpa: Optional[float] = None
    upright_only: Optional[bool] = None
    zone: Optional[str] = None
    retrieval_priority: Optional[int] = None

    def as_row(self) -> Dict[str, object]:
        return {k: v for k, v in asdict(self).items() if v is not None}


@dataclass
class Instance:
    name: str
    instance_class: int
    n_items: int
    seed: int
    pallet: Pallet
    items: List[Item]
    extended: bool
    stats: Dict[str, object] = field(default_factory=dict)


# --------------------------------------------------------------------------- #
# 5. Core sampling routines (paper faithful)
# --------------------------------------------------------------------------- #

def _bounded(value: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, value))


def sample_ratios(rng: random.Random) -> Tuple[float, float]:
    """Draw (depth/width, height/width) from the fitted distributions."""
    while True:
        p = rng.gauss(DW_RATIO_MEAN, DW_RATIO_SD)
        if DW_RATIO_BOUNDS[0] <= p <= DW_RATIO_BOUNDS[1]:
            break
    q = _bounded(rng.lognormvariate(HW_RATIO_MU, HW_RATIO_SIGMA), *HW_RATIO_BOUNDS)
    return p, q


def sample_volume_dm3(rng: random.Random, instance_class: int) -> Tuple[float, int]:
    """Pick a volume category according to the class mix, then a volume in it."""
    weights = CLASS_MIX[instance_class]
    cat = rng.choices(range(5), weights=weights, k=1)[0]
    lo, hi = VOLUME_CATEGORIES[cat]
    return rng.uniform(lo, hi), cat + 1


def sample_repetition(rng: random.Random) -> int:
    """Number of physical cases carrying the same SKU (mixed cases => small)."""
    return max(1, int(round(rng.lognormvariate(REP_MU, REP_SIGMA))))


def sample_box(rng: random.Random, instance_class: int, pallet: Pallet
               ) -> Tuple[float, float, float, float, int]:
    """
    Draw one geometrically feasible box.

    Returns (width, depth, height, volume_dm3, volume_category) in mm / dm^3.
    Rejection sampling guarantees the box fits into the loading space in at
    least one axis-aligned orientation and is not absurdly thin.
    """
    for _attempt in range(1000):
        v_dm3, cat = sample_volume_dm3(rng, instance_class)
        p, q = sample_ratios(rng)
        v_mm3 = v_dm3 * 1e6
        w = (v_mm3 / (p * q)) ** (1.0 / 3.0)
        d, h = p * w, q * w
        w, d, h = round(w, 1), round(d, 1), round(h, 1)

        if min(w, d, h) < MIN_SIDE_MM:
            continue
        if h > pallet.height:
            continue
        # footprint must fit with the longer side along the pallet width
        long_side, short_side = max(w, d), min(w, d)
        if long_side > pallet.width or short_side > pallet.depth:
            continue
        return w, d, h, round(w * d * h / 1e6, 4), cat

    raise RuntimeError("Rejection sampling failed - check pallet dimensions.")


# --------------------------------------------------------------------------- #
# 6. Extension attributes
# --------------------------------------------------------------------------- #

def sample_family(rng: random.Random) -> Family:
    return rng.choices(FAMILIES, weights=[f.share for f in FAMILIES], k=1)[0]


def attach_extensions(rng: random.Random, item: Item, fam: Family) -> None:
    """Attach weight, family, load bearing, orientation and picking data."""
    for _ in range(50):
        density = rng.uniform(*fam.density_kg_m3)
        weight = density * item.volume_dm3 / 1000.0        # dm^3 -> m^3
        if weight <= MAX_CASE_WEIGHT_KG:
            break
    else:
        weight = MAX_CASE_WEIGHT_KG

    fragile = rng.random() < fam.fragile_prob

    # Load-bearing capacity: max pressure allowed on the top face.
    # Convention adapted from Junqueira et al. (2012): sigma ~ U[0, 3*h] with
    # the box weight taken as its volume; here expressed in kPa so that the
    # stacking constraint reads  sum(weight above)*g / footprint <= sigma.
    if fragile:
        load_bearing = round(rng.uniform(0.5, 3.0), 2)
    else:
        base = 3.0 * (item.height / 1000.0)                 # m
        load_bearing = round(rng.uniform(0.4, 1.0) * base * 9.81 * 1000.0 / 1000.0
                             * rng.uniform(1.5, 4.0), 2)
        load_bearing = max(load_bearing, 4.0)

    item.weight_kg = round(weight, 2)
    item.family = fam.name
    item.is_food = fam.is_food
    item.is_chemical = fam.is_chemical
    item.fragile = fragile
    item.load_bearing_kpa = load_bearing
    item.upright_only = rng.random() < fam.upright_prob
    item.zone = fam.zone


def assign_retrieval_priorities(items: Sequence[Item], rng: random.Random) -> None:
    """
    Retrieval priority 1..K: the order in which store areas are served.
    Items of the same zone share a priority, with a little noise so that the
    picking sequence is not perfectly correlated with the product family.
    """
    order = {z: i + 1 for i, z in enumerate(ZONE_PICK_ORDER)}
    k = len(ZONE_PICK_ORDER)
    for it in items:
        base = order.get(it.zone or "general", k)
        if rng.random() < 0.10:                       # 10 % exceptions
            base = _bounded(base + rng.choice([-1, 1]), 1, k)
        it.retrieval_priority = int(base)


# --------------------------------------------------------------------------- #
# 7. Instance assembly
# --------------------------------------------------------------------------- #

def generate_instance(n_items: int,
                      instance_class: int = 1,
                      seed: int = 0,
                      pallet: Pallet = PALLET_EURO_180,
                      extended: bool = True,
                      name: Optional[str] = None) -> Instance:
    """
    Generate one MCPP instance.

    The item loop follows the paper: SKUs are drawn one at a time together with
    a repetition count, and identical copies are appended until `n_items` cases
    have been created. This is what produces the "mixed case" signature -
    high variety, few duplicates (industry ratio 166,406 / 73,978 ~ 2.25).
    """
    if instance_class not in CLASS_MIX:
        raise ValueError(f"instance_class must be in {sorted(CLASS_MIX)}")
    if n_items < 1:
        raise ValueError("n_items must be >= 1")

    rng = random.Random(seed)
    items: List[Item] = []
    sku = 0

    while len(items) < n_items:
        w, d, h, v, cat = sample_box(rng, instance_class, pallet)
        fam = sample_family(rng) if extended else None
        reps = min(sample_repetition(rng), n_items - len(items))
        sku += 1
        for _ in range(reps):
            it = Item(id=len(items) + 1, sku=sku, width=w, depth=d, height=h,
                      volume_dm3=v, volume_category=cat)
            if extended and fam is not None:
                attach_extensions(rng, it, fam)
            items.append(it)

    if extended:
        assign_retrieval_priorities(items, rng)

    inst_name = name or f"mcpp_c{instance_class}_n{n_items:04d}_s{seed}"
    inst = Instance(name=inst_name, instance_class=instance_class, n_items=n_items,
                    seed=seed, pallet=pallet, items=items, extended=extended)
    inst.stats = compute_stats(inst)
    return inst


# --------------------------------------------------------------------------- #
# 8. Statistics, lower bounds and validation
# --------------------------------------------------------------------------- #

def continuous_lower_bound(items: Sequence[Item], pallet: Pallet) -> int:
    """L0: volume bound on the number of pallets (Martello et al. 2000)."""
    total = sum(it.volume_dm3 for it in items)
    return max(1, math.ceil(total / pallet.volume_dm3))


def weight_lower_bound(items: Sequence[Item], pallet: Pallet) -> Optional[int]:
    if not items or items[0].weight_kg is None:
        return None
    total = sum(it.weight_kg or 0.0 for it in items)
    return max(1, math.ceil(total / pallet.max_payload_kg))


def scaled_centroid_stats(items: Sequence[Item]
                          ) -> Tuple[Tuple[float, float, float, float], float]:
    """
    Centroid of (w, d, h, v) plus the mean Euclidean distance to the centroid
    computed on standardized features - the validation used in the paper
    ("we used the scale function in R before calculating the distance values").
    """
    cols = [[it.width for it in items], [it.depth for it in items],
            [it.height for it in items], [it.volume_dm3 for it in items]]
    centroid = tuple(statistics.fmean(c) for c in cols)
    sds = [statistics.pstdev(c) or 1.0 for c in cols]
    total = 0.0
    for it in items:
        vals = (it.width, it.depth, it.height, it.volume_dm3)
        total += math.sqrt(sum(((v - m) / s) ** 2
                               for v, m, s in zip(vals, centroid, sds)))
    return centroid, total / len(items)


def compute_stats(inst: Instance) -> Dict[str, object]:
    items, pallet = inst.items, inst.pallet
    centroid, avg_dist = scaled_centroid_stats(items)
    total_v = sum(it.volume_dm3 for it in items)
    lb = continuous_lower_bound(items, pallet)
    stats: Dict[str, object] = {
        "n_items": len(items),
        "n_distinct_skus": len({it.sku for it in items}),
        "item_sku_ratio": round(len(items) / len({it.sku for it in items}), 3),
        "total_volume_dm3": round(total_v, 2),
        "mean_volume_dm3": round(total_v / len(items), 3),
        "pallet_volume_dm3": round(pallet.volume_dm3, 2),
        "lower_bound_pallets_L0": lb,
        "items_per_pallet_at_LB": round(len(items) / lb, 1),
        "mean_item_to_bin_volume_ratio": round(total_v / len(items) / pallet.volume_dm3, 5),
        "centroid_w_d_h_v": [round(c, 2) for c in centroid],
        "avg_scaled_distance": round(avg_dist, 3),
        "volume_category_share_pct": _category_share(items),
    }
    if inst.extended:
        w_total = sum(it.weight_kg or 0.0 for it in items)
        stats.update({
            "total_weight_kg": round(w_total, 1),
            "mean_weight_kg": round(w_total / len(items), 2),
            "lower_bound_pallets_weight": weight_lower_bound(items, pallet),
            "share_chemical_pct": round(
                100.0 * sum(1 for it in items if it.is_chemical) / len(items), 1),
            "share_food_pct": round(
                100.0 * sum(1 for it in items if it.is_food) / len(items), 1),
            "share_fragile_pct": round(
                100.0 * sum(1 for it in items if it.fragile) / len(items), 1),
            "share_upright_only_pct": round(
                100.0 * sum(1 for it in items if it.upright_only) / len(items), 1),
        })
    return stats


def _category_share(items: Sequence[Item]) -> List[float]:
    n = len(items)
    return [round(100.0 * sum(1 for it in items if it.volume_category == c) / n, 2)
            for c in range(1, 6)]


def validate_against_paper(n_items: int = 2000, replications: int = 20,
                           seed0: int = 1000) -> str:
    """Reproduce Table 4 (generated columns) of Elhedhli et al. (2019)."""
    lines = ["Validation against Elhedhli et al. (2019), Table 4",
             "(bin = 1200 x 800 x 2055 mm, geometry only)", ""]
    header = (f"{'Class':>5} | {'centroid (w, d, h, v) - reproduced':<42} | "
              f"{'paper':<42} | {'avg dist':>8} | {'paper':>6}")
    lines += [header, "-" * len(header)]
    for cls in sorted(CLASS_MIX):
        cents, dists = [], []
        for r in range(replications):
            inst = generate_instance(n_items, cls, seed0 + r,
                                     PALLET_ELHEDHLI, extended=False)
            c, dd = scaled_centroid_stats(inst.items)
            cents.append(c)
            dists.append(dd)
        mean_c = tuple(statistics.fmean(c[i] for c in cents) for i in range(4))
        paper_c = PAPER_GENERATED_CENTROIDS[cls]
        lines.append(
            f"{cls:>5} | ({mean_c[0]:7.2f}, {mean_c[1]:7.2f}, {mean_c[2]:7.2f}, "
            f"{mean_c[3]:6.2f}){'':<7} | ({paper_c[0]:7.2f}, {paper_c[1]:7.2f}, "
            f"{paper_c[2]:7.2f}, {paper_c[3]:6.2f}){'':<7} | "
            f"{statistics.fmean(dists):8.2f} | {PAPER_GENERATED_AVG_DIST[cls]:6.2f}")
    lines += ["", f"({replications} replications of {n_items} items per class.)"]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# 9. Exporters
# --------------------------------------------------------------------------- #

def to_json(inst: Instance) -> str:
    payload = {
        "name": inst.name,
        "source": "Elhedhli, Gzara & Yildiz (2019), INFORMS J. Optimization 1(4)",
        "generator_version": "1.0",
        "instance_class": inst.instance_class,
        "seed": inst.seed,
        "extended": inst.extended,
        "pallet": asdict(inst.pallet),
        "statistics": inst.stats,
        "items": [it.as_row() for it in inst.items],
    }
    return json.dumps(payload, indent=2)


def to_csv(inst: Instance, path: str) -> None:
    rows = [it.as_row() for it in inst.items]
    fieldnames = list(rows[0].keys())
    with open(path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def to_bpp_txt(inst: Instance) -> str:
    """
    Plain 3DBPP format compatible with Martello/Pisinger-style readers:
        line 1: n
        line 2: W D H
        then  : id w d h
    """
    p = inst.pallet
    out = [str(len(inst.items)),
           f"{int(p.width)} {int(p.depth)} {int(p.height)}"]
    out += [f"{it.id} {it.width:g} {it.depth:g} {it.height:g}" for it in inst.items]
    return "\n".join(out) + "\n"


def summary_text(inst: Instance) -> str:
    s = inst.stats
    lines = [f"Instance {inst.name}",
             f"  class {inst.instance_class}, seed {inst.seed}, "
             f"pallet {inst.pallet.name} "
             f"({inst.pallet.width:.0f} x {inst.pallet.depth:.0f} x {inst.pallet.height:.0f} mm)",
             f"  items {s['n_items']}, distinct SKUs {s['n_distinct_skus']} "
             f"(ratio {s['item_sku_ratio']}, industry reference 2.25)",
             f"  total volume {s['total_volume_dm3']} dm3, "
             f"mean item {s['mean_volume_dm3']} dm3",
             f"  volume lower bound {s['lower_bound_pallets_L0']} pallets "
             f"-> {s['items_per_pallet_at_LB']} items/pallet",
             f"  volume-category mix (%) {s['volume_category_share_pct']}",
             f"  centroid (w,d,h,v) {s['centroid_w_d_h_v']}, "
             f"avg scaled distance {s['avg_scaled_distance']}"]
    if inst.extended:
        lines += [f"  weight {s['total_weight_kg']} kg total, "
                  f"{s['mean_weight_kg']} kg mean, "
                  f"weight bound {s['lower_bound_pallets_weight']} pallets",
                  f"  food {s['share_food_pct']} %, chemical {s['share_chemical_pct']} %, "
                  f"fragile {s['share_fragile_pct']} %, "
                  f"upright-only {s['share_upright_only_pct']} %"]
    return "\n".join(lines)


def to_solver_txt(inst: Instance, max_bins: Optional[int] = None) -> str:
    """Return the native input format consumed by this project's solver.

    The D-Wave example accepts integer dimensions and groups identical cases
    through a quantity column. MCPP dimensions are generated in millimetres,
    so they are rounded to the nearest millimetre rather than converted to
    centimetres. Items sharing an SKU are guaranteed to share their geometry.
    Extended attributes remain available in the companion JSON/CSV export;
    the inherited solver currently consumes geometry only.
    """
    if max_bins is None:
        max_bins = continuous_lower_bound(inst.items, inst.pallet)
    if max_bins < continuous_lower_bound(inst.items, inst.pallet):
        raise ValueError(
            f"solver max bins must be at least the volume lower bound "
            f"{continuous_lower_bound(inst.items, inst.pallet)}"
        )

    grouped: Dict[int, Tuple[int, int, int, int]] = {}
    for item in inst.items:
        dims = (
            max(1, int(round(item.width))),
            max(1, int(round(item.depth))),
            max(1, int(round(item.height))),
        )
        if item.sku in grouped:
            quantity, width, depth, height = grouped[item.sku]
            if (width, depth, height) != dims:
                raise ValueError(f"SKU {item.sku} has inconsistent dimensions")
            grouped[item.sku] = (quantity + 1, width, depth, height)
        else:
            grouped[item.sku] = (1, *dims)

    pallet_dims = (
        int(round(inst.pallet.width)),
        int(round(inst.pallet.depth)),
        int(round(inst.pallet.height)),
    )
    lines = [
        f"# Max num of bins : {max_bins}",
        "# Bin dimensions (L * W * H): " + " ".join(map(str, pallet_dims)),
        "",
        "  case_id    quantity    length    width    height",
        "---------  ----------  --------  -------  --------",
    ]
    for sku, (quantity, length, width, height) in grouped.items():
        lines.append(
            f"{sku:<9}  {quantity:<10}  {length:<8}  {width:<7}  {height}"
        )
    return "\n".join(lines) + "\n"


def write_instance(inst: Instance, outdir: str, formats: Sequence[str],
                   solver_bins: Optional[int] = None) -> List[str]:
    os.makedirs(outdir, exist_ok=True)
    written = []
    if "json" in formats:
        p = os.path.join(outdir, inst.name + ".json")
        with open(p, "w", encoding="utf-8") as fh:
            fh.write(to_json(inst))
        written.append(p)
    if "csv" in formats:
        p = os.path.join(outdir, inst.name + ".csv")
        to_csv(inst, p)
        written.append(p)
    if "txt" in formats:
        p = os.path.join(outdir, inst.name + ".txt")
        with open(p, "w", encoding="utf-8") as fh:
            fh.write(to_bpp_txt(inst))
        written.append(p)
    if "solver" in formats:
        p = os.path.join(outdir, inst.name + "_solver.txt")
        with open(p, "w", encoding="utf-8") as fh:
            fh.write(to_solver_txt(inst, solver_bins))
        written.append(p)
    return written


# --------------------------------------------------------------------------- #
# 10. Command line interface
# --------------------------------------------------------------------------- #

def _add_common(sp: argparse.ArgumentParser) -> None:
    sp.add_argument("-o", "--outdir", default="instances", help="output directory")
    sp.add_argument("--pallet", choices=sorted(PALLETS), default="euro-180",
                    help="loading space (default: Euro pallet, 1800 mm height)")
    sp.add_argument("--formats", default="json,csv",
                    help="comma separated subset of json,csv,txt,solver")
    sp.add_argument("--solver-bins", type=int, default=None,
                    help="maximum bins in solver output (default: volume lower bound)")
    sp.add_argument("--no-extended", action="store_true",
                    help="geometry only, exactly as in the paper")


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(
        description="Realistic MCPP / 3DBPP instance generator "
                    "(Elhedhli, Gzara & Yildiz 2019).")
    sub = ap.add_subparsers(dest="cmd", required=True)

    s1 = sub.add_parser("single", help="generate one instance")
    s1.add_argument("--class", dest="cls", type=int, default=1, choices=[1, 2, 3, 4])
    s1.add_argument("--items", type=int, default=1000)
    s1.add_argument("--seed", type=int, default=0)
    _add_common(s1)

    s2 = sub.add_parser("batch", help="generate a full benchmark set")
    s2.add_argument("--classes", default="1,2,3,4")
    s2.add_argument("--sizes", default=",".join(str(s) for s in PAPER_SIZES))
    s2.add_argument("--replications", type=int, default=5)
    s2.add_argument("--seed0", type=int, default=0)
    _add_common(s2)

    s3 = sub.add_parser("validate", help="reproduce Table 4 of the paper")
    s3.add_argument("--items", type=int, default=2000)
    s3.add_argument("--replications", type=int, default=20)

    args = ap.parse_args(argv)

    if args.cmd == "validate":
        print(validate_against_paper(args.items, args.replications))
        return 0

    pallet = PALLETS[args.pallet]
    formats = [f.strip() for f in args.formats.split(",") if f.strip()]
    unsupported_formats = set(formats) - {"json", "csv", "txt", "solver"}
    if unsupported_formats:
        ap.error(f"unsupported formats: {', '.join(sorted(unsupported_formats))}")
    extended = not args.no_extended

    if args.cmd == "single":
        inst = generate_instance(args.items, args.cls, args.seed, pallet, extended)
        print(summary_text(inst))
        for p in write_instance(inst, args.outdir, formats, args.solver_bins):
            print("  wrote", p)
        return 0

    # batch
    classes = [int(c) for c in args.classes.split(",")]
    sizes = [int(s) for s in args.sizes.split(",")]
    index = []
    count = 0
    for cls in classes:
        for n in sizes:
            for r in range(1, args.replications + 1):
                seed = args.seed0 + 100000 * cls + 100 * r + n
                name = f"mcpp_c{cls}_n{n:04d}_i{r}"
                inst = generate_instance(n, cls, seed, pallet, extended, name)
                write_instance(inst, args.outdir, formats, args.solver_bins)
                index.append({"name": name, "class": cls, "items": n,
                              "replication": r, "seed": seed, **inst.stats})
                count += 1
    idx_path = os.path.join(args.outdir, "index.csv")
    with open(idx_path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(index[0].keys()))
        writer.writeheader()
        for row in index:
            writer.writerow(row)
    print(f"generated {count} instances in {args.outdir}")
    print("index:", idx_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
